SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

DROP TABLE IF EXISTS `club`;
DROP TABLE IF EXISTS `club_member`;
DROP TABLE IF EXISTS `club_wine_stat`;
DROP TABLE IF EXISTS `game_point`;
DROP TABLE IF EXISTS `game_result`;
DROP TABLE IF EXISTS `game_settings`;
DROP TABLE IF EXISTS `game_setup`;
DROP TABLE IF EXISTS `judgement`;
DROP TABLE IF EXISTS `lobby`;
DROP TABLE IF EXISTS `lobby_data`;
DROP TABLE IF EXISTS `lobby_history`;
DROP TABLE IF EXISTS `match_history`;
DROP TABLE IF EXISTS `result_data`;
DROP TABLE IF EXISTS `settings_history`;
DROP TABLE IF EXISTS `user`;
DROP TABLE IF EXISTS `user_guesses`;
DROP TABLE IF EXISTS `user_results`;

COMMIT;